apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scadium.fullname" . }}-config
  labels: {{- include "scadium.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.api.env.NODE_ENV | quote }}
  JWT_ACCESS_TTL: {{ .Values.api.env.JWT_ACCESS_TTL | quote }}
  THROTTLE_TTL: {{ .Values.api.env.THROTTLE_TTL | quote }}
  THROTTLE_LIMIT: {{ .Values.api.env.THROTTLE_LIMIT | quote }}
  {{- if .Values.redis.external.enabled }}
  REDIS_URL: {{ required "redis.external.url is required when redis.external.enabled" .Values.redis.external.url | quote }}
  {{- else }}
  REDIS_URL: {{ printf "redis://%s-redis:6379" (include "scadium.fullname" .) | quote }}
  {{- end }}
  CORS_ORIGIN: {{ printf "https://%s" .Values.ingress.host | quote }}
