// Regenerate the shared cross-impl golden-vector fixture from the Node
// @scadium/fair engine. Run with:  node scripts/gen-golden.mjs
//
// The committed fixture (src/__fixtures__/golden.json) is the single source of
// truth that the Node engine, the browser WebCrypto engine
// (apps/web/src/lib/fair-browser.ts), and the Rust program
// (programs/scadium_lottery/src/lib.rs) must all reproduce. Changing any
// derivation means regenerating this AND updating all three test suites.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  crashPoint,
  coinflipResult,
  blackjackDeal,
  jackpotRoll,
  jackpotWinningTicket,
  lotteryDraw,
  lotteryFinalEntropy,
  padClientSeed32,
} from '../dist/index.js';

const here = dirname(fileURLToPath(import.meta.url));

// Fixed (NOT random) inputs. The first vector is byte-identical to the Rust
// `golden_vector_lockstep` test so the program can reuse this fixture.
const INPUTS = [
  { label: 'rust-lottery-golden', serverSeed: 'deadbeef'.repeat(8), clientSeed: 'cafebabe12345678', nonce: 0, slot: (i) => i },
  { label: 'all-a-seed', serverSeed: 'a'.repeat(64), clientSeed: 'player-one', nonce: 1, slot: () => 0xff },
  { label: 'mixed', serverSeed: 'b'.repeat(64), clientSeed: 'scadium', nonce: 7, slot: (i) => (i * 7 + 3) & 0xff },
];

// A fixed pot above 2^53 lamports so the jackpot ticket locks the BigInt
// wide-modulus reduction (the legacy Number(total) path could not represent it).
const JACKPOT_POT = (1n << 53n) + 1n;

const toHex = (u8) => Buffer.from(u8).toString('hex');

const vectors = INPUTS.map(({ label, serverSeed, clientSeed, nonce, slot }) => {
  const slotBytes = Uint8Array.from({ length: 32 }, (_, i) => slot(i));
  const clientSeed32 = padClientSeed32(clientSeed);
  const entropy = lotteryFinalEntropy(serverSeed, clientSeed32, slotBytes, nonce);
  const lottery = lotteryDraw(serverSeed, clientSeed32, slotBytes, nonce);
  return {
    label,
    serverSeed,
    clientSeed,
    nonce,
    slotHashHex: toHex(slotBytes),
    crash: crashPoint(serverSeed, clientSeed, nonce),
    coinflip: coinflipResult(serverSeed, clientSeed, nonce),
    blackjack: blackjackDeal(serverSeed, clientSeed, nonce, 10).map((c) => `${c.rank}${c.suit}`),
    jackpotRoll: jackpotRoll(serverSeed, clientSeed, nonce).toString(),
    jackpotPot: JACKPOT_POT.toString(),
    jackpotTicket: jackpotWinningTicket(serverSeed, clientSeed, nonce, JACKPOT_POT).toString(),
    lottery: {
      entropyHex: entropy.toString('hex'),
      digits: lottery.digits,
      encoded: lottery.encoded,
    },
  };
});

const out = {
  $note:
    'Shared cross-impl golden vectors. Generated by packages/fair/scripts/gen-golden.mjs. Node (@scadium/fair), browser (apps/web/src/lib/fair-browser.ts), and Rust (programs/scadium_lottery) MUST all reproduce these. Changing any derivation requires regenerating this file and updating all three test suites.',
  vectors,
};

writeFileSync(resolve(here, '../src/__fixtures__/golden.json'), `${JSON.stringify(out, null, 2)}\n`);
console.log(`Wrote ${vectors.length} golden vectors.`);
